### ISSUE TITLE
NSSpeechDriver: 'super' object has no attribute 'init'

### ISSUE THREAD

**Issue by iuga** [parente/pyttsx#33]
Hi All !
I grab this code from the examples:
```python
import pyttsx
engine = pyttsx.init()
engine.say('How are you today?')
engine.runAndWait()
```
but is failing with a:
```bash
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    engine = pyttsx.init()
  File ".../venv/lib/python2.7/site-packages/pyttsx/__init__.py", line 39, in init
    eng = Engine(driverName, debug)
  File ".../venv/lib/python2.7/site-packages/pyttsx/engine.py", line 45, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File ".../venv/lib/python2.7/site-packages/pyttsx/driver.py", line 66, in __init__
    self._driver = self._module.buildDriver(weakref.proxy(self))
  File ".../venv/lib/python2.7/site-packages/pyttsx/drivers/nsss.py", line 24, in buildDriver
    return NSSpeechDriver.alloc().initWithProxy(proxy)
  File ".../venv/lib/python2.7/site-packages/pyttsx/drivers/nsss.py", line 28, in initWithProxy
    self = super(NSSpeechDriver, self).init()
AttributeError: 'super' object has no attribute 'init'
```

Running it on:
```
OSX Yosemite 10.10.3
```
```
Python 2.7.6
```
```
pyobjc==3.0.4
pyobjc-core==3.0.4
pyttsx==1.1
```

Any thoughts ? Any help will be really appreciated !

**Comment by uranusjr** [comment]
It seems like that this is a problem in PyObjC. I [raised this problem and was offered a solution](https://bitbucket.org/ronaldoussoren/pyobjc/issues/131/attributeerror-super-object-has-no).

This problem does not exist with the pyobjc and Python shipped with OS X, so it is either a problem with PyObjC 3.x, or a non-built-in Python installation. Unfortunately I can not able to build PyObjC on 10.10 to verify either.

**Comment by isaac-rks** [comment]
Hi uranusjr, thanks for the above solution, I can confirm it works on homebrew Python 2.7.9

**Comment by anshtyagi0** [comment]
Having same issue Python 3.11.3 installed using arch -x86_64 brew

**Comment by anshtyagi0** [comment]
@uranusjr

**Comment by usersina** [comment]
Same issue with `python 3.11.5` on `Ventura 13.5.1 (22G90)`
